import type { SeoGapFinderResult } from "@/types/seo-gap-finder";

/**
 * Datos de demostración estáticos para la landing pública de SEO Gap Finder AI.
 * No se llama a APIs; solo sirve para vista previa de gráficos e interacción.
 */
export const SEO_GAP_LANDING_DEMO: SeoGapFinderResult = {
  executiveSummary:
    "La SERP mezcla intención transaccional con guías y comparativas. Hay hueco en long-tail de tallas/colores y en preguntas de uso real; los marketplaces dominan la cabecera pero dejan espacio en contenido de nicho y FAQs específicas.",
  opportunities: [
    {
      keyword: "zapatillas running mujer amortiguación",
      type: "transaccional",
      cluster: "Amortiguación",
      score: 92,
      opportunityLevel: "alta",
      action: "Crear PLP filtrada + bloque comparativa de suelas",
      title: "Zapatillas running mujer con amortiguación máxima",
      url: "/zapatillas-running-mujer-amortiguacion",
      demandTier: "medio",
      monthlyVolumeEstimate: 5400,
      trendsInterest: 78,
    },
    {
      keyword: "mejores zapatillas para correr asfalto mujer",
      type: "informacional",
      cluster: "Superficie",
      score: 88,
      opportunityLevel: "alta",
      action: "Publicar guía + tabla comparativa 5 modelos",
      title: "Mejores zapatillas para asfalto (mujer) en 2026",
      url: "/guia-zapatillas-asfalto-mujer",
      demandTier: "bajo",
      monthlyVolumeEstimate: 1900,
      trendsInterest: 71,
    },
    {
      keyword: "zapatillas running mujer talla 42",
      type: "transaccional",
      cluster: "Tallas",
      score: 86,
      opportunityLevel: "alta",
      action: "Landing tallas grandes + stock en tiempo real",
      title: "Zapatillas running mujer talla 42 — stock actualizado",
      url: "/zapatillas-running-mujer-talla-42",
      demandTier: "nicho",
      monthlyVolumeEstimate: 480,
      trendsInterest: 62,
    },
    {
      keyword: "zapatillas correr mujer pronadoras",
      type: "informacional",
      cluster: "Pisada",
      score: 84,
      opportunityLevel: "alta",
      action: "FAQ pisada + enlaces a fichas recomendadas",
      title: "Zapatillas para pronadoras: qué buscar al comprar",
      url: "/zapatillas-pronadoras-mujer",
      demandTier: "bajo",
      monthlyVolumeEstimate: 1200,
      trendsInterest: 58,
    },
    {
      keyword: "zapatillas trail mujer impermeables",
      type: "transaccional",
      cluster: "Trail",
      score: 81,
      opportunityLevel: "alta",
      action: "Categoría trail + filtros clima/Gore-Tex",
      title: "Zapatillas trail mujer impermeables",
      url: "/zapatillas-trail-mujer-impermeables",
      demandTier: "medio",
      monthlyVolumeEstimate: 3200,
      trendsInterest: 65,
    },
    {
      keyword: "cuánto duran zapatillas running",
      type: "informacional",
      cluster: "Mantenimiento",
      score: 79,
      opportunityLevel: "media",
      action: "Artículo + vídeo corto + CTA a renovación",
      title: "Cuánto duran las zapatillas running: señales de cambio",
      url: "/blog/cuanto-duran-zapatillas-running",
      demandTier: "bajo",
      monthlyVolumeEstimate: 2400,
      trendsInterest: 55,
    },
    {
      keyword: "zapatillas running mujer ofertas hoy",
      type: "transaccional",
      cluster: "Ofertas",
      score: 77,
      opportunityLevel: "media",
      action: "Bloque ofertas rotativas + schema Offer",
      title: "Ofertas zapatillas running mujer — selección diaria",
      url: "/ofertas-zapatillas-running-mujer",
      demandTier: "alto",
      monthlyVolumeEstimate: 8100,
      trendsInterest: 82,
    },
    {
      keyword: "zapatillas running mujer ligeras competición",
      type: "transaccional",
      cluster: "Competición",
      score: 75,
      opportunityLevel: "media",
      action: "Colección competición + peso en gramos en ficha",
      title: "Zapatillas running ligeras para competición (mujer)",
      url: "/zapatillas-competicion-mujer-ligeras",
      demandTier: "bajo",
      monthlyVolumeEstimate: 980,
      trendsInterest: 48,
    },
    {
      keyword: "zapatillas running vs walking diferencias",
      type: "informacional",
      cluster: "Educación",
      score: 72,
      opportunityLevel: "media",
      action: "Post comparativa + enlaces internos a categorías",
      title: "Running vs walking: diferencias en la zapatilla",
      url: "/blog/running-vs-walking-zapatillas",
      demandTier: "bajo",
      monthlyVolumeEstimate: 1100,
      trendsInterest: 44,
    },
    {
      keyword: "plantillas zapatillas running mujer",
      type: "transaccional",
      cluster: "Accesorios",
      score: 70,
      opportunityLevel: "media",
      action: "Cross-sell plantillas + bundle en checkout",
      title: "Plantillas para zapatillas running mujer",
      url: "/plantillas-running-mujer",
      demandTier: "medio",
      monthlyVolumeEstimate: 2600,
      trendsInterest: 52,
    },
    {
      keyword: "zapatillas running mujer marca X opiniones",
      type: "navegacional",
      cluster: "Marca",
      score: 68,
      opportunityLevel: "media",
      action: "Página marca + agregación reseñas verificadas",
      title: "Opiniones zapatillas running mujer — marca líder",
      url: "/marca/zapatillas-running-mujer-opiniones",
      demandTier: "medio",
      monthlyVolumeEstimate: 4500,
      trendsInterest: 66,
    },
    {
      keyword: "zapatillas running mujer invierno frío",
      type: "transaccional",
      cluster: "Estación",
      score: 66,
      opportunityLevel: "media",
      action: "Landing estacional + contenido térmico",
      title: "Zapatillas running mujer para invierno",
      url: "/zapatillas-running-mujer-invierno",
      demandTier: "nicho",
      monthlyVolumeEstimate: 620,
      trendsInterest: 41,
    },
    {
      keyword: "devolución zapatillas running talla incorrecta",
      type: "informacional",
      cluster: "Postventa",
      score: 64,
      opportunityLevel: "baja",
      action: "FAQ política cambios + guía de tallaje",
      title: "Cambiar talla zapatillas running: guía rápida",
      url: "/ayuda/cambio-talla-zapatillas-running",
      demandTier: "nicho",
      monthlyVolumeEstimate: 320,
      trendsInterest: 38,
    },
    {
      keyword: "zapatillas running mujer sostenibles recicladas",
      type: "informacional",
      cluster: "Sostenibilidad",
      score: 62,
      opportunityLevel: "baja",
      action: "Storytelling materiales + certificaciones",
      title: "Zapatillas running sostenibles para mujer",
      url: "/zapatillas-running-mujer-sostenibles",
      demandTier: "nicho",
      monthlyVolumeEstimate: 890,
      trendsInterest: 59,
    },
    {
      keyword: "zapatillas running mujer para principiantes",
      type: "informacional",
      cluster: "Principiantes",
      score: 60,
      opportunityLevel: "baja",
      action: "Guía inicio + pack starter",
      title: "Zapatillas running mujer para empezar a correr",
      url: "/guia-principiantes-zapatillas-running-mujer",
      demandTier: "bajo",
      monthlyVolumeEstimate: 1500,
      trendsInterest: 47,
    },
    {
      keyword: "zapatillas running mujer outlet últimas unidades",
      type: "transaccional",
      cluster: "Outlet",
      score: 58,
      opportunityLevel: "baja",
      action: "Outlet dinámico + urgencia suave",
      title: "Outlet zapatillas running mujer — últimas unidades",
      url: "/outlet-zapatillas-running-mujer",
      demandTier: "medio",
      monthlyVolumeEstimate: 2900,
      trendsInterest: 73,
    },
  ],
  meta: {
    keyword: "zapatillas running mujer",
    domain: "mitienda-running.es",
    country: "es",
    language: "es",
    organicCount: 10,
    competitorsCrawled: 7,
    crawlWarnings: [],
    userSiteKeywordsSample: ["running", "mujer", "zapatillas", "trail", "ofertas"],
    generatedAt: new Date().toISOString(),
    trendsDataPoints: 16,
  },
};
