import type { SeoGapFinderResult } from "@/types/seo-gap-finder";

/**
 * Datos de demostración estáticos para la landing pública de SEO Gap Finder AI.
 * Caso de ejemplo basado en análisis tipo «cremas de belleza» + dominio Bess Skin (demo).
 * No se llama a APIs; solo sirve para vista previa de gráficos e interacción.
 */
export const SEO_GAP_LANDING_DEMO: SeoGapFinderResult = {
  executiveSummary:
    "La SERP mezcla grandes retailers (Druni, Amazon, Douglas) con blogs de comparativas y marcas de nicho. Hay hueco en long-tail de tipo de piel, ingredientes activos y rutinas cortas; tu sitio puede ganar con guías hiper-contextualizadas y fichas que respondan a ‘cómo elegir’ antes que solo a ‘comprar’.",
  opportunities: [
    {
      keyword: "cremas faciales hidratantes piel sensible",
      type: "transaccional",
      cluster: "Piel sensible",
      score: 93,
      opportunityLevel: "alta",
      action: "PLP + filtros por tipo de piel y sin perfume",
      title: "Cremas faciales hidratantes para piel sensible",
      url: "/cremas-faciales-hidratantes-piel-sensible",
      demandTier: "medio",
      monthlyVolumeEstimate: 4200,
      trendsInterest: 76,
    },
    {
      keyword: "mejores cremas antiarrugas 40 años",
      type: "informacional",
      cluster: "Anti-edad",
      score: 90,
      opportunityLevel: "alta",
      action: "Guía + tabla comparativa con activos (retinol, péptidos)",
      title: "Mejores cremas antiarrugas a los 40: qué mirar",
      url: "/guia-cremas-antiarrugas-40-anos",
      demandTier: "bajo",
      monthlyVolumeEstimate: 1800,
      trendsInterest: 68,
    },
    {
      keyword: "crema vitamina c serum rutina mañana",
      type: "informacional",
      cluster: "Ingredientes",
      score: 88,
      opportunityLevel: "alta",
      action: "Post rutina AM + bundle vitamina C + SPF",
      title: "Rutina de mañana: sérum vitamina C y crema",
      url: "/blog/rutina-manana-vitamina-c",
      demandTier: "bajo",
      monthlyVolumeEstimate: 1400,
      trendsInterest: 62,
    },
    {
      keyword: "cremas de belleza naturales sin parabenos",
      type: "transaccional",
      cluster: "Clean beauty",
      score: 86,
      opportunityLevel: "alta",
      action: "Categoría ‘clean’ + sellos y transparencia INCI",
      title: "Cremas de belleza naturales sin parabenos",
      url: "/cremas-belleza-naturales-sin-parabenos",
      demandTier: "medio",
      monthlyVolumeEstimate: 3100,
      trendsInterest: 71,
    },
    {
      keyword: "diferencia crema dia y noche facial",
      type: "informacional",
      cluster: "Educación",
      score: 84,
      opportunityLevel: "alta",
      action: "FAQ ampliada + vídeo corto vertical",
      title: "Crema de día vs noche: diferencias clave",
      url: "/blog/crema-dia-vs-noche",
      demandTier: "bajo",
      monthlyVolumeEstimate: 2200,
      trendsInterest: 54,
    },
    {
      keyword: "cremas faciales con ácido hialurónico baratas",
      type: "transaccional",
      cluster: "Ingredientes",
      score: 82,
      opportunityLevel: "alta",
      action: "Rango precio + comparador 3 formatos",
      title: "Cremas con ácido hialurónico: calidad-precio",
      url: "/cremas-acido-hialuronico",
      demandTier: "medio",
      monthlyVolumeEstimate: 5800,
      trendsInterest: 79,
    },
    {
      keyword: "crema facial piel grasa poros",
      type: "transaccional",
      cluster: "Tipo de piel",
      score: 80,
      opportunityLevel: "alta",
      action: "Landing piel grasa + non-comedogénico en ficha",
      title: "Cremas faciales para piel grasa y poros",
      url: "/cremas-faciales-piel-grasa",
      demandTier: "medio",
      monthlyVolumeEstimate: 3600,
      trendsInterest: 66,
    },
    {
      keyword: "orden aplicar crema contorno ojos serum",
      type: "informacional",
      cluster: "Rutina",
      score: 78,
      opportunityLevel: "media",
      action: "Infografía capas + enlaces a productos",
      title: "Orden correcto: sérum, contorno y crema",
      url: "/blog/orden-rutina-facial",
      demandTier: "nicho",
      monthlyVolumeEstimate: 950,
      trendsInterest: 48,
    },
    {
      keyword: "cremas de belleza hombre barba irritación",
      type: "informacional",
      cluster: "Hombre",
      score: 76,
      opportunityLevel: "media",
      action: "Post nicho + línea hombre si aplica",
      title: "Cremas faciales hombre con barba: irritación",
      url: "/cremas-facial-hombre-barba",
      demandTier: "nicho",
      monthlyVolumeEstimate: 720,
      trendsInterest: 43,
    },
    {
      keyword: "crema facial con color spf 50",
      type: "transaccional",
      cluster: "BB/CC cream",
      score: 74,
      opportunityLevel: "media",
      action: "Categoría SPF maquillaje + tonos",
      title: "Cremas con color y SPF 50: protección diaria",
      url: "/cremas-color-spf-50",
      demandTier: "medio",
      monthlyVolumeEstimate: 4900,
      trendsInterest: 74,
    },
    {
      keyword: "regalar set cremas faciales premium",
      type: "transaccional",
      cluster: "Regalo",
      score: 72,
      opportunityLevel: "media",
      action: "Pack regalo + envío y mensaje",
      title: "Sets de cremas faciales para regalar",
      url: "/sets-cremas-regalo",
      demandTier: "bajo",
      monthlyVolumeEstimate: 1600,
      trendsInterest: 51,
    },
    {
      keyword: "cremas faciales embarazadas ingredientes evitar",
      type: "informacional",
      cluster: "Seguridad",
      score: 70,
      opportunityLevel: "media",
      action: "Guía médica-SEO + disclaimer",
      title: "Cremas faciales en el embarazo: qué evitar",
      url: "/blog/cremas-faciales-embarazo",
      demandTier: "nicho",
      monthlyVolumeEstimate: 1100,
      trendsInterest: 46,
    },
    {
      keyword: "crema facial noche reparadora invierno",
      type: "transaccional",
      cluster: "Estacional",
      score: 68,
      opportunityLevel: "media",
      action: "Landing invierno + bálsamos y ceramidas",
      title: "Cremas de noche reparadoras para invierno",
      url: "/cremas-noche-invierno",
      demandTier: "bajo",
      monthlyVolumeEstimate: 1300,
      trendsInterest: 42,
    },
    {
      keyword: "marca cremas españolas farmacia online",
      type: "navegacional",
      cluster: "Marca / origen",
      score: 66,
      opportunityLevel: "baja",
      action: "Página ‘hecho en España’ + trust",
      title: "Cremas faciales de marcas españolas",
      url: "/marcas-espanolas-cremas-faciales",
      demandTier: "medio",
      monthlyVolumeEstimate: 2800,
      trendsInterest: 58,
    },
    {
      keyword: "cremas de belleza veganas cruelty free",
      type: "informacional",
      cluster: "Valores",
      score: 64,
      opportunityLevel: "baja",
      action: "Storytelling + certificación Leaping Bunny / PETA",
      title: "Cremas de belleza veganas y cruelty free",
      url: "/cremas-belleza-veganas",
      demandTier: "bajo",
      monthlyVolumeEstimate: 1900,
      trendsInterest: 61,
    },
    {
      keyword: "cremas faciales ofertas black friday belleza",
      type: "transaccional",
      cluster: "Ofertas",
      score: 60,
      opportunityLevel: "baja",
      action: "Página estacional + countdown suave",
      title: "Ofertas en cremas faciales — Black Friday",
      url: "/ofertas-cremas-faciales",
      demandTier: "alto",
      monthlyVolumeEstimate: 7200,
      trendsInterest: 81,
    },
  ],
  meta: {
    keyword: "cremas de belleza",
    domain: "bess-skinhealth.com",
    country: "es",
    language: "es",
    organicCount: 10,
    competitorsCrawled: 7,
    crawlWarnings: [],
    userSiteKeywordsSample: ["crema", "piel", "belleza", "facial", "hidratante"],
    generatedAt: new Date().toISOString(),
    trendsDataPoints: 16,
  },
};
